<?xml version="1.0" encoding="utf-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>org.microbean</groupId>
  <artifactId>microbean-scopelet</artifactId>
  <version>0.0.11-SNAPSHOT</version>

  <name>microBean™ Scopelet</name>
  <description>microBean™ Scopelet: Utility classes for implementing scopelets.</description>
  <inceptionYear>2023</inceptionYear>
  <url>https://microbean.github.io/microbean-scopelet</url>

  <organization>
    <name>microBean™</name>
    <url>http://microbean.systems/</url>
  </organization>

  <licenses>
    <license>
      <comments>The Apache License, Version 2.0</comments>
      <distribution>repo</distribution>
      <name>Apache License 2.0</name>
      <url>https://www.apache.org/licenses/LICENSE-2.0.txt</url>
    </license>
  </licenses>

  <developers>
    <developer>
      <id>ljnelson</id>
      <name>Laird Nelson</name>
      <email>ljnelson@gmail.com</email>
      <url>https://about.me/lairdnelson</url>
      <roles>
        <role>architect</role>
        <role>developer</role>
      </roles>
      <timezone>-8</timezone>
    </developer>
  </developers>

  <scm>
    <connection>${scm.url}</connection>
    <developerConnection>${scm.url}</developerConnection>
    <url>https://github.com/microbean/microbean-scopelet/</url>
    <tag>HEAD</tag>
  </scm>

  <issueManagement>
    <system>Github</system>
    <url>https://github.com/microbean/microbean-scopelet/issues</url>
  </issueManagement>

  <distributionManagement>
    <site>
      <id>Github Pages</id>
      <name>microBean™ Scopelet Site</name>
      <url>https://microbean.github.io/microbean-scopelet/</url>
    </site>
  </distributionManagement>

  <properties>

    <java.util.logging.config.file>${project.basedir}/src/test/java/logging.properties</java.util.logging.config.file>

    <!-- maven-compiler-plugin properties -->
    <maven.compiler.release>16</maven.compiler.release>
    <maven.compiler.showDeprecation>true</maven.compiler.showDeprecation>
    <maven.compiler.showWarnings>true</maven.compiler.showWarnings>

    <!-- maven-javadoc-plugin properties -->
    <bottom><![CDATA[Copyright &copy; ${project.inceptionYear}&ndash;{currentYear}, <a href="${project.organization.url}" target="_top">${project.organization.name}</a>. All rights reserved.]]></bottom>
    <doctitle>&lt;a href="${project.url}" target="_top"&gt;&lt;span style="font-family:Lobster, cursive;"&gt;µb&lt;/span&gt; ${project.artifactId}&lt;/a&gt; ${project.version}</doctitle>
    <links>https://microbean.github.io/microbean-assign/apidocs/,https://microbean.github.io/microbean-attributes/apidocs/,https://microbean.github.io/microbean-bean/apidocs/,https://microbean.github.io/microbean-construct/apidocs/,https://microbean.github.io/microbean-reference/apidocs/</links>
    <sourcetab>2</sourcetab>

    <!-- maven-release-plugin properties -->
    <!-- See http://central.sonatype.org/pages/apache-maven.html#performing-a-release-deployment-with-the-maven-release-plugin -->
    <goals>deploy,post-site,scm-publish:publish-scm</goals>
    <releaseProfiles>deployment</releaseProfiles>
    <scmCommentPrefix>[maven-release-plugin] [skip ci]</scmCommentPrefix>
    <tagNameFormat>v@{project.version}</tagNameFormat>

    <!-- maven-scm-publish-plugin properties;
         see https://maven.apache.org/plugins/maven-scm-publish-plugin/publish-scm-mojo.html -->
    <scmpublish.content>${project.reporting.outputDirectory}</scmpublish.content>
    <scmpublish.pubScmUrl>${project.scm.developerConnection}</scmpublish.pubScmUrl>
    <scmpublish.scm.branch>gh-pages</scmpublish.scm.branch>

    <!-- maven-site-plugin properties -->
    <maven.site.deploy.skip>true</maven.site.deploy.skip>
    <relativizeDecorationLinks>false</relativizeDecorationLinks>

    <!-- central-publishing-maven-plugin properties -->
    <deploymentName>${project.name} v${project.version}</deploymentName>
    
    <!-- Other properties -->
    <project.build.sourceEncoding>UTF8</project.build.sourceEncoding>
    <project.reporting.outputEncoding>UTF8</project.reporting.outputEncoding>
    <scm.url>scm:git:git@github.com:microbean/microbean-scopelet.git</scm.url>

    <!-- <surefire.useModulePath>false</surefire.useModulePath> -->

  </properties>

  <dependencyManagement>
    <dependencies>

      <!-- BOM dependencies. -->

      <dependency>
        <groupId>org.junit</groupId>
        <artifactId>junit-bom</artifactId>
        <version>6.0.1</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>

      <!-- Normal dependencies. -->

      <dependency>
        <groupId>org.microbean</groupId>
        <artifactId>microbean-assign</artifactId>
        <version>0.0.11</version>
      </dependency>

      <dependency>
        <groupId>org.microbean</groupId>
        <artifactId>microbean-attributes</artifactId>
        <version>0.0.5</version>
      </dependency>

      <dependency>
        <groupId>org.microbean</groupId>
        <artifactId>microbean-bean</artifactId>
        <version>0.0.22</version>
      </dependency>

      <dependency>
        <groupId>org.microbean</groupId>
        <artifactId>microbean-construct</artifactId>
        <version>0.0.18</version>
      </dependency>

      <dependency>
        <groupId>org.microbean</groupId>
        <artifactId>microbean-event</artifactId> <!-- scopelets fire events -->
        <version>0.0.3</version>
      </dependency>

      <dependency>
        <groupId>org.microbean</groupId>
        <artifactId>microbean-reference</artifactId>
        <version>0.0.5</version>
      </dependency>

    </dependencies>
  </dependencyManagement>

  <dependencies>

    <dependency>
      <groupId>org.microbean</groupId>
      <artifactId>microbean-assign</artifactId>
      <scope>compile</scope>
    </dependency>

    <dependency>
      <groupId>org.microbean</groupId>
      <artifactId>microbean-attributes</artifactId>
      <scope>compile</scope>
    </dependency>

    <dependency>
      <groupId>org.microbean</groupId>
      <artifactId>microbean-bean</artifactId>
      <scope>compile</scope>
    </dependency>

    <dependency>
      <groupId>org.microbean</groupId>
      <artifactId>microbean-construct</artifactId>
      <scope>compile</scope>
    </dependency>

    <dependency>
      <groupId>org.microbean</groupId>
      <artifactId>microbean-event</artifactId> <!-- scopelets fire events -->
      <scope>compile</scope>
    </dependency>
    
    <dependency>
      <groupId>org.microbean</groupId>
      <artifactId>microbean-reference</artifactId>
      <scope>compile</scope>
    </dependency>

    <!-- Test-scoped dependencies. -->

    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter-api</artifactId>
      <scope>test</scope>
    </dependency>

    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter-engine</artifactId>
      <scope>test</scope>
    </dependency>

  </dependencies>

  <build>
    <pluginManagement>
      <plugins>
        <plugin>
          <artifactId>maven-antrun-plugin</artifactId>
          <version>3.2.0</version>
        </plugin>
        <plugin>
          <artifactId>maven-assembly-plugin</artifactId>
          <version>3.8.0</version>
        </plugin>
        <plugin>
          <artifactId>maven-checkstyle-plugin</artifactId>
          <version>3.6.0</version>
          <configuration>
            <checkstyleRules>
              <module name="Checker">
                <module name="BeforeExecutionExclusionFileFilter">
                  <property name="fileNamePattern" value="module\-info\.java$" />
                </module>
                <module name="FileTabCharacter">
                  <property name="eachLine" value="true" />
                </module>
                <module name="JavadocPackage" />
                <module name="LineLength">
                  <property name="max" value="160" />
                </module>
                <module name="NewlineAtEndOfFile">
                  <property name="lineSeparator" value="lf" />
                </module>
                <module name="TreeWalker">
                  <module name="AnnotationLocation">
                    <property name="allowSamelineSingleParameterlessAnnotation" value="false" />
                  </module>
                  <module name="AnnotationUseStyle" />
                  <module name="ArrayTypeStyle" />
                  <module name="AvoidNestedBlocks" />
                  <module name="AvoidStarImport" />
                  <module name="ClassMemberImpliedModifier" />
                  <module name="CommentsIndentation" />
                  <module name="DeclarationOrder" />
                  <module name="DefaultComesLast" />
                  <module name="EmptyBlock" />
                  <module name="EmptyCatchBlock" />
                  <module name="EmptyStatement" />
                  <module name="EqualsHashCode" />
                  <module name="ExplicitInitialization" />
                  <module name="FinalClass" />
                  <module name="FinalLocalVariable">
                    <property name="tokens" value="VARIABLE_DEF,PARAMETER_DEF" />
                  </module>
                  <module name="HideUtilityClassConstructor" />
                  <module name="InnerAssignment" />
                  <module name="InnerTypeLast" />
                  <module name="InterfaceIsType" />
                  <module name="InterfaceMemberImpliedModifier">
                    <property name="violateImpliedAbstractMethod" value="false" />
                  </module>
                  <module name="InvalidJavadocPosition" />
                  <module name="JavadocContentLocationCheck" />
                  <module name="JavadocMissingWhitespaceAfterAsterisk" />
                  <module name="JavadocParagraph" />
                  <module name="JavadocStyle" />
                  <module name="JavadocVariable">
                    <property name="scope" value="protected" />
                  </module>
                  <module name="LeftCurly" />
                  <module name="MethodTypeParameterName" />
                  <module name="MissingCtor" />
                  <module name="MissingDeprecated" />
                  <module name="MissingJavadocMethod" />
                  <module name="MissingJavadocPackage" />
                  <module name="MissingJavadocType">
                    <property name="scope" value="protected" />
                  </module>
                  <module name="MissingOverride" />
                  <module name="MultipleVariableDeclarations" />
                  <module name="ModifierOrder" />
                  <module name="NeedBraces" />
                  <module name="NoArrayTrailingComma" />
                  <module name="NoFinalizer" />
                  <module name="NonEmptyAtclauseDescription" />
                  <module name="OneStatementPerLine" />
                  <module name="OneTopLevelClass" />
                  <module name="OuterTypeFilename" />
                  <module name="OverloadMethodsDeclarationOrder" />
                  <module name="PackageDeclaration" />
                  <module name="RedundantImport" />
                  <module name="RegexpSinglelineJava">
                    <property name="format" value="\s+$" />
                    <property name="message" value="File contains trailing whitespace." />
                  </module>
                  <module name="RequireEmptyLineBeforeBlockTagGroup" />
                  <module name="RequireThis" />
                  <module name="RightCurly" />
                  <module name="SummaryJavadocCheck" />
                  <module name="SuppressWarningsHolder" />
                  <module name="UnnecessarySemicolonAfterOuterTypeDeclaration" />
                  <module name="UnnecessarySemicolonAfterTypeMemberDeclaration" />
                  <module name="UnnecessarySemicolonInEnumeration" />
                  <module name="UnnecessarySemicolonInTryWithResources" />
                  <module name="UnusedImports" />
                  <module name="UnusedLocalVariable" />
                  <module name="UpperEll" />
                  <module name="VariableDeclarationUsageDistance" />
                </module>
                <property name="charset" value="${project.build.sourceEncoding}" />
                <property name="tabWidth" value="2" />
              </module>
            </checkstyleRules>
            <propertyExpansion>
              project.basedir=${project.basedir}
              project.build.sourceEncoding=${project.build.sourceEncoding}
            </propertyExpansion>
          </configuration>
          <dependencies>
            <dependency>
              <groupId>com.puppycrawl.tools</groupId>
              <artifactId>checkstyle</artifactId>
              <version>12.3.0</version>
            </dependency>
          </dependencies>
        </plugin>
        <plugin>
          <artifactId>maven-clean-plugin</artifactId>
          <version>3.5.0</version>
          <configuration>
            <filesets>
              <fileset>
                <directory>${basedir}</directory>
                <includes>
                  <include>src/**/*~</include>
                  <include>*~</include>
                </includes>
              </fileset>
            </filesets>
          </configuration>
        </plugin>
        <plugin>
          <artifactId>maven-compiler-plugin</artifactId>
          <version>3.14.1</version>
          <configuration>
            <compilerArgs>
              <arg>-Xlint:all</arg>
              <arg>-parameters</arg>
            </compilerArgs>
          </configuration>
        </plugin>
        <plugin>
          <artifactId>maven-dependency-plugin</artifactId>
          <version>3.9.0</version>
        </plugin>
        <plugin>
          <artifactId>maven-deploy-plugin</artifactId>
          <version>3.1.4</version>
        </plugin>
        <plugin>
          <artifactId>maven-enforcer-plugin</artifactId>
          <version>3.6.2</version>
        </plugin>
        <plugin>
          <artifactId>maven-gpg-plugin</artifactId>
          <version>3.2.8</version>
        </plugin>
        <plugin>
          <artifactId>maven-install-plugin</artifactId>
          <version>3.1.4</version>
        </plugin>
        <plugin>
          <artifactId>maven-jar-plugin</artifactId>
          <version>3.5.0</version>
        </plugin>
        <plugin>
          <artifactId>maven-javadoc-plugin</artifactId>
          <version>3.12.0</version>
          <configuration>
            <docfilessubdirs>true</docfilessubdirs>
            <tags>
              <tag>
                <name>microbean.idempotency</name>
                <placement>m</placement>
                <head>Idempotency:</head>
              </tag>
              <tag>
                <name>microbean.nullability</name>
                <placement>cfm</placement>
                <head>Nullability:</head>
              </tag>
              <tag>
                <name>microbean.threadsafety</name>
                <placement>fmpt</placement>
                <head>Thread Safety:</head>
              </tag>
            </tags>
          </configuration>
        </plugin>
        <plugin>
          <artifactId>maven-plugin-plugin</artifactId>
          <version>3.9.0</version>
        </plugin>
        <plugin>
          <artifactId>maven-project-info-reports-plugin</artifactId>
          <version>3.9.0</version>
        </plugin>
        <plugin>
          <artifactId>maven-release-plugin</artifactId>
          <version>3.3.1</version>
        </plugin>
        <plugin>
          <artifactId>maven-resources-plugin</artifactId>
          <version>3.4.0</version>
        </plugin>
        <plugin>
          <artifactId>maven-scm-plugin</artifactId>
          <version>2.2.1</version>
        </plugin>
        <plugin>
          <artifactId>maven-scm-publish-plugin</artifactId>
          <version>3.3.0</version>
        </plugin>
        <plugin>
          <artifactId>maven-site-plugin</artifactId>
          <version>3.21.0</version>
        </plugin>
        <plugin>
          <artifactId>maven-source-plugin</artifactId>
          <version>3.4.0</version>
          <executions>
            <execution>
              <id>attach-sources</id>
              <goals>
                <goal>jar-no-fork</goal>
              </goals>
            </execution>
          </executions>
        </plugin>
        <plugin>
          <artifactId>maven-surefire-plugin</artifactId>
          <version>3.5.4</version>
        </plugin>
        <plugin>
          <artifactId>maven-toolchains-plugin</artifactId>
          <version>3.2.0</version>
        </plugin>
        <plugin>
          <groupId>com.github.spotbugs</groupId>
          <artifactId>spotbugs-maven-plugin</artifactId>
          <version>4.9.8.2</version>
        </plugin>
        <plugin>
          <groupId>org.codehaus.mojo</groupId>
          <artifactId>versions-maven-plugin</artifactId>
          <version>2.20.1</version>
        </plugin>
        <plugin>
          <groupId>io.smallrye</groupId>
          <artifactId>jandex-maven-plugin</artifactId>
          <version>3.5.3</version>
        </plugin>
        <plugin>
          <groupId>org.sonatype.central</groupId>
          <artifactId>central-publishing-maven-plugin</artifactId>
          <version>0.9.0</version>
          <extensions>true</extensions>
          <configuration>
            <publishingServerId>central.sonatype.com</publishingServerId>
          </configuration>
        </plugin>
      </plugins>
    </pluginManagement>

    <plugins>
      <plugin>
        <artifactId>maven-enforcer-plugin</artifactId>
        <executions>
          <execution>
            <id>enforce-maven</id>
            <goals>
              <goal>enforce</goal>
            </goals>
            <configuration>
              <rules>
                <requireJavaVersion>
                  <version>23</version>
                </requireJavaVersion>
                <requireMavenVersion>
                  <version>3.9.9</version>
                </requireMavenVersion>
              </rules>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <artifactId>maven-surefire-plugin</artifactId>
        <configuration>
          <properties>
            <!-- See https://junit.org/junit5/docs/snapshot/user-guide/#running-tests-build-maven-config-params -->
            <configurationParameters>
              junit.jupiter.execution.parallel.enabled=true
              junit.jupiter.execution.parallel.mode.default=concurrent
            </configurationParameters>
          </properties>
          <systemPropertyVariables>
            <java.util.logging.config.file>${java.util.logging.config.file}</java.util.logging.config.file>
            <project.build.directory>${project.build.directory}</project.build.directory>
            <project.build.testOutputDirectory>${project.build.testOutputDirectory}</project.build.testOutputDirectory>
          </systemPropertyVariables>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.sonatype.central</groupId>
        <artifactId>central-publishing-maven-plugin</artifactId>
      </plugin>
    </plugins>

    <resources>
      <resource>
        <directory>src/main/resources</directory>
      </resource>

      <resource>
        <targetPath>META-INF</targetPath>
        <directory>${project.basedir}</directory>
        <includes>
          <include>LICENSE</include>
        </includes>
      </resource>
    </resources>
  </build>

  <reporting>
    <plugins>
      <!--
      <plugin>
        <artifactId>maven-checkstyle-plugin</artifactId>
        <reportSets>
          <reportSet>
            <reports>
              <report>checkstyle</report>
            </reports>
          </reportSet>
        </reportSets>
      </plugin>
      -->
      <plugin>
        <artifactId>maven-javadoc-plugin</artifactId>
        <reportSets>
          <reportSet>
            <reports>
              <report>javadoc-no-fork</report>
            </reports>
          </reportSet>
        </reportSets>
      </plugin>
    </plugins>
  </reporting>

  <profiles>
    <profile>
      <id>deployment</id>
      <build>
        <plugins>
          <plugin>
            <artifactId>maven-gpg-plugin</artifactId>
            <executions>
              <execution>
                <id>sign-artifacts</id>
                <phase>verify</phase>
                <goals>
                  <goal>sign</goal>
                </goals>
              </execution>
            </executions>
          </plugin>
          <plugin>
            <artifactId>maven-javadoc-plugin</artifactId>
            <executions>
              <execution>
                <id>attach-javadocs</id>
                <goals>
                  <goal>jar</goal>
                </goals>
              </execution>
            </executions>
          </plugin>
          <plugin>
            <artifactId>maven-source-plugin</artifactId>
          </plugin>
        </plugins>
      </build>
    </profile>
  </profiles>


</project>
